package com.ems.serviceimpl;

import com.ems.dto.EmployeeDTO;
import com.ems.entity.Employee;
import com.ems.exception.DuplicateEmailException;
import com.ems.exception.ResourceNotFoundException;
import com.ems.repository.EmployeeRepository;
import com.ems.service.EmployeeService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

/**
 * EmployeeServiceImpl - Concrete implementation of EmployeeService.
 *
 * Key annotations:
 *   @Service        -> Marks this as a Spring-managed service bean (stereotype of @Component).
 *                      Spring will automatically discover and register it.
 *
 *   @Transactional  -> At class level: every public method runs in a DB transaction.
 *                      If a method throws an unchecked exception, the transaction
 *                      rolls back automatically — no partial commits.
 *                      Read-only methods override this with readOnly=true for performance.
 *
 *   @RequiredArgsConstructor (Lombok):
 *                      Generates a constructor for all `final` fields.
 *                      Spring uses constructor injection (best practice over @Autowired).
 *
 *   @Slf4j (Lombok):
 *                      Injects a SLF4J logger as `log`. Use it instead of System.out.println.
 *
 * Responsibilities of this layer:
 *   - Business logic & validation (e.g., uniqueness checks)
 *   - Mapping between DTO ↔ Entity
 *   - Calling the repository for DB operations
 *   - Throwing meaningful business exceptions
 */
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class EmployeeServiceImpl implements EmployeeService {

    /** Injected via constructor (generated by @RequiredArgsConstructor) */
    private final EmployeeRepository employeeRepository;

    // ======================================================================
    // CREATE
    // ======================================================================

    /**
     * Creates a new employee after checking email uniqueness.
     *
     * Flow:
     *   1. Check if email is already taken → throw DuplicateEmailException if yes
     *   2. Map DTO → Entity
     *   3. Persist entity via repository.save()
     *   4. Map saved Entity → DTO and return
     */
    @Override
    public EmployeeDTO createEmployee(EmployeeDTO employeeDTO) {
        log.info("Creating new employee with email: {}", employeeDTO.getEmail());

        // Step 1: Enforce email uniqueness
        if (employeeRepository.existsByEmail(employeeDTO.getEmail())) {
            log.warn("Email already in use: {}", employeeDTO.getEmail());
            throw new DuplicateEmailException(employeeDTO.getEmail());
        }

        // Step 2: Convert DTO → Entity
        Employee employee = mapToEntity(employeeDTO);

        // Step 3: Save to DB (Hibernate generates INSERT SQL)
        Employee savedEmployee = employeeRepository.save(employee);
        log.info("Employee created successfully with ID: {}", savedEmployee.getId());

        // Step 4: Convert saved Entity → DTO and return
        return mapToDTO(savedEmployee);
    }

    // ======================================================================
    // READ ALL
    // ======================================================================

    /**
     * Fetches all employees from the database.
     *
     * @Transactional(readOnly=true):
     *   - Hibernate skips dirty-checking (no need to track changes)
     *   - Database can use read replicas
     *   - Slightly better performance for SELECT operations
     *
     * Uses Java Streams to transform List<Entity> → List<DTO>.
     */
    @Override
    @Transactional(readOnly = true)
    public List<EmployeeDTO> getAllEmployees() {
        log.info("Fetching all employees");

        List<Employee> employees = employeeRepository.findAll();
        log.info("Found {} employees", employees.size());

        // Stream: for each Employee entity, call mapToDTO(), collect into a list
        return employees.stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());
    }

    // ======================================================================
    // READ BY ID
    // ======================================================================

    /**
     * Fetches a single employee by ID.
     *
     * findById() returns Optional<Employee>:
     *   - orElseThrow() unwraps the value if present
     *   - or throws ResourceNotFoundException if empty (ID not found)
     */
    @Override
    @Transactional(readOnly = true)
    public EmployeeDTO getEmployeeById(Long id) {
        log.info("Fetching employee with ID: {}", id);

        Employee employee = employeeRepository.findById(id)
                .orElseThrow(() -> {
                    log.warn("Employee not found with ID: {}", id);
                    return new ResourceNotFoundException("Employee", "id", id);
                });

        return mapToDTO(employee);
    }

    // ======================================================================
    // UPDATE
    // ======================================================================

    /**
     * Updates an existing employee's details.
     *
     * Flow:
     *   1. Verify the employee exists (throws 404 if not)
     *   2. Check if the new email conflicts with ANOTHER employee's email
     *      (allow same employee to keep their email)
     *   3. Apply all field updates to the managed entity
     *   4. @Transactional auto-flushes changes to DB (no explicit save needed)
     *   5. Return updated DTO
     *
     * Note: employeeRepository.save() is called explicitly here for clarity,
     * but within a @Transactional context Hibernate would flush dirty changes
     * automatically at commit time.
     */
    @Override
    public EmployeeDTO updateEmployee(Long id, EmployeeDTO employeeDTO) {
        log.info("Updating employee with ID: {}", id);

        // Step 1: Find existing employee or throw 404
        Employee existingEmployee = employeeRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Employee", "id", id));

        // Step 2: Check email conflict with a DIFFERENT employee
        if (employeeRepository.existsByEmailAndIdNot(employeeDTO.getEmail(), id)) {
            log.warn("Email conflict during update: {} is used by another employee",
                    employeeDTO.getEmail());
            throw new DuplicateEmailException(employeeDTO.getEmail());
        }

        // Step 3: Apply updates to all fields
        existingEmployee.setName(employeeDTO.getName());
        existingEmployee.setEmail(employeeDTO.getEmail());
        existingEmployee.setDepartment(employeeDTO.getDepartment());
        existingEmployee.setDesignation(employeeDTO.getDesignation());
        existingEmployee.setSalary(employeeDTO.getSalary());

        // Step 4: Persist (Hibernate generates UPDATE SQL)
        Employee updatedEmployee = employeeRepository.save(existingEmployee);
        log.info("Employee with ID {} updated successfully", id);

        // Step 5: Return mapped DTO
        return mapToDTO(updatedEmployee);
    }

    // ======================================================================
    // DELETE
    // ======================================================================

    /**
     * Deletes an employee by ID.
     *
     * We first check existence so we can throw our custom 404
     * instead of Spring Data's EmptyResultDataAccessException.
     */
    @Override
    public void deleteEmployee(Long id) {
        log.info("Deleting employee with ID: {}", id);

        // Verify employee exists before attempting delete
        if (!employeeRepository.existsById(id)) {
            log.warn("Cannot delete — employee not found with ID: {}", id);
            throw new ResourceNotFoundException("Employee", "id", id);
        }

        employeeRepository.deleteById(id);
        log.info("Employee with ID {} deleted successfully", id);
    }

    // ======================================================================
    // PRIVATE MAPPER METHODS
    // ======================================================================

    /**
     * Maps Employee Entity → EmployeeDTO.
     *
     * Uses Lombok's @Builder pattern for clean, readable object construction.
     * In larger projects, consider using MapStruct for auto-generated mappers.
     */
    private EmployeeDTO mapToDTO(Employee employee) {
        return EmployeeDTO.builder()
                .id(employee.getId())
                .name(employee.getName())
                .email(employee.getEmail())
                .department(employee.getDepartment())
                .designation(employee.getDesignation())
                .salary(employee.getSalary())
                .build();
    }

    /**
     * Maps EmployeeDTO → Employee Entity.
     *
     * Note: `id` is intentionally NOT set here for create operations
     * (JPA will auto-generate it). For update, the ID is set on the
     * existing entity retrieved from the DB.
     */
    private Employee mapToEntity(EmployeeDTO employeeDTO) {
        return Employee.builder()
                .name(employeeDTO.getName())
                .email(employeeDTO.getEmail())
                .department(employeeDTO.getDepartment())
                .designation(employeeDTO.getDesignation())
                .salary(employeeDTO.getSalary())
                .build();
    }
}
